# -*- coding: utf-8 -*-

# Macro Begin: /home/abogaers/Documents/FreeCADCFDWorkbench/TestCases/macros/porousZone.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD
import _CommandCfdAnalysis
import CfdAnalysis
import CfdPhysicsSelection
import CfdFluidMaterial
import CfdInitialiseFlowField
import CfdSolverFoam
import _CommandCfdFluidBoundary
import _CommandCfdMeshCartFromShape
import CfdMeshCart
import _CommandCfdMeshRegion
import CfdMeshRegion
import _CommandCfdPorousZone
import CfdZone
import FemGui
import CfdFluidBoundary
import CfdZone
import _CommandCfdPorousZone

analysis = CfdAnalysis.makeCfdAnalysis('CfdAnalysis')
FemGui.setActiveAnalysis(analysis)
analysis.Member = analysis.Member + [CfdPhysicsSelection.makeCfdPhysicsSelection()]
analysis.Member = analysis.Member + [CfdFluidMaterial.makeCfdFluidMaterial('FluidProperties')]
analysis.Member = analysis.Member + [CfdInitialiseFlowField.makeCfdInitialFlowField()]
analysis.Member = analysis.Member + [CfdSolverFoam.makeCfdSolverFoam()]

phys = FreeCAD.ActiveDocument.PhysicsModel.PhysicsModel
phys['Time'] = 'Steady'
phys['Flow'] = 'Incompressible'
phys['Turbulence'] = 'Laminar'
phys['TurbulenceModel'] = 'None'
phys['Thermal'] = None
FreeCAD.ActiveDocument.PhysicsModel.PhysicsModel = phys

mat = FreeCAD.ActiveDocument.FluidProperties.Material
mat['Density'] = '1.2e-09 kg/mm^3'
mat['DynamicViscosity'] = '1.8e-08 kg/(mm*s)'
FreeCAD.ActiveDocument.FluidProperties.Material = mat

# Values are converted to SI units and stored (eg. m/s)
init = FreeCAD.ActiveDocument.InitialiseFields.InitialVariables
init['PotentialFoam'] = True
init['Ux'] = 0.0
init['Uy'] = 0.0
init['Uz'] = 0.0
init['Pressure'] = 0.0
init['UseInletTurbulenceValues'] = False
init['omega'] = 1.00007366139
init['k'] = 0.01
FreeCAD.ActiveDocument.InitialiseFields.InitialVariables = init
#Gui.getDocument("porousZone").getObject("Box").Visibility=True
FemGui.getActiveAnalysis().Member = FemGui.getActiveAnalysis().Member + [CfdFluidBoundary.makeCfdFluidBoundary()]

# Values are converted to SI units and stored (eg. m/s)
bc = FreeCAD.ActiveDocument.CfdFluidBoundary.BoundarySettings
bc['BoundaryType'] = 'inlet'
bc['BoundarySubtype'] = 'uniformVelocity'
bc['ThermalBoundaryType'] = 'fixedValue'
bc['VelocityIsCartesian'] = True
bc['Ux'] = 0.0
bc['Uy'] = 0.0
bc['Uz'] = 1.0
bc['VelocityMag'] = 0.0
bc['DirectionFace'] = 'Box:Face5'
bc['ReverseNormal'] = False
bc['MassFlowRate'] = 0.0
bc['VolFlowRate'] = 0.0
bc['Pressure'] = 0.0
bc['SlipRatio'] = 0.0
bc['TurbulenceInletSpecification'] = 'intensityAndLengthScale'
bc['TurbulentKineticEnergy'] = 0.01
bc['SpecificDissipationRate'] = 1.00007366139
bc['TurbulenceIntensity'] = 0.1
bc['TurbulenceLengthScale'] = 0.1
bc['PressureDropCoeff'] = 0.0
bc['ScreenWireDiameter'] = 0.0001
bc['ScreenSpacing'] = 0.0
bc['PorousBaffleMethod'] = 0
FreeCAD.ActiveDocument.CfdFluidBoundary.BoundarySettings = bc
FreeCAD.ActiveDocument.CfdFluidBoundary.Label = 'inlet'
FreeCAD.ActiveDocument.CfdFluidBoundary.References.append(('Box', 'Face5'))
FreeCAD.getDocument('porousZone').recompute()
FemGui.getActiveAnalysis().Member = FemGui.getActiveAnalysis().Member + [CfdFluidBoundary.makeCfdFluidBoundary()]

# Values are converted to SI units and stored (eg. m/s)
bc = FreeCAD.ActiveDocument.CfdFluidBoundary001.BoundarySettings
bc['BoundaryType'] = 'outlet'
bc['BoundarySubtype'] = 'staticPressure'
bc['ThermalBoundaryType'] = 'fixedValue'
bc['VelocityIsCartesian'] = True
bc['Ux'] = 0.0
bc['Uy'] = 0.0
bc['Uz'] = 0.0
bc['VelocityMag'] = 0.0
bc['DirectionFace'] = 'Box:Face6'
bc['ReverseNormal'] = False
bc['MassFlowRate'] = 0.0
bc['VolFlowRate'] = 0.0
bc['Pressure'] = 0.0
bc['SlipRatio'] = 0.0
bc['TurbulenceInletSpecification'] = 'intensityAndLengthScale'
bc['TurbulentKineticEnergy'] = 0.01
bc['SpecificDissipationRate'] = 1.00007366139
bc['TurbulenceIntensity'] = 0.1
bc['TurbulenceLengthScale'] = 0.1
bc['PressureDropCoeff'] = 0.0
bc['ScreenWireDiameter'] = 0.0001
bc['ScreenSpacing'] = 0.0
bc['PorousBaffleMethod'] = 0
FreeCAD.ActiveDocument.CfdFluidBoundary001.BoundarySettings = bc
FreeCAD.ActiveDocument.CfdFluidBoundary001.Label = 'outlet'
FreeCAD.ActiveDocument.CfdFluidBoundary001.References.append(('Box', 'Face6'))
FreeCAD.getDocument('porousZone').recompute()
FemGui.getActiveAnalysis().Member = FemGui.getActiveAnalysis().Member + [CfdFluidBoundary.makeCfdFluidBoundary()]

# Values are converted to SI units and stored (eg. m/s)
bc = FreeCAD.ActiveDocument.CfdFluidBoundary002.BoundarySettings
bc['BoundaryType'] = 'wall'
bc['BoundarySubtype'] = 'slip'
bc['ThermalBoundaryType'] = 'fixedValue'
bc['VelocityIsCartesian'] = True
bc['Ux'] = 0.0
bc['Uy'] = 0.0
bc['Uz'] = 0.0
bc['VelocityMag'] = 0.0
bc['DirectionFace'] = 'Box:Face4'
bc['ReverseNormal'] = False
bc['MassFlowRate'] = 0.0
bc['VolFlowRate'] = 0.0
bc['Pressure'] = 0.0
bc['SlipRatio'] = 0.0
bc['TurbulenceInletSpecification'] = 'intensityAndLengthScale'
bc['TurbulentKineticEnergy'] = 0.01
bc['SpecificDissipationRate'] = 1.00007366139
bc['TurbulenceIntensity'] = 0.1
bc['TurbulenceLengthScale'] = 0.1
bc['PressureDropCoeff'] = 0.0
bc['ScreenWireDiameter'] = 0.0001
bc['ScreenSpacing'] = 0.0
bc['PorousBaffleMethod'] = 0
FreeCAD.ActiveDocument.CfdFluidBoundary002.BoundarySettings = bc
FreeCAD.ActiveDocument.CfdFluidBoundary002.Label = 'wall'
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Box', 'Face4'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Box', 'Face1'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Box', 'Face3'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Box', 'Face2'))
FreeCAD.getDocument('porousZone').recompute()
#Gui.getDocument("porousZone").getObject("CfdFluidBoundary002").Visibility=False
CfdMeshCart.makeCfdMeshCart('Box_CartesianMesh')
App.ActiveDocument.ActiveObject.Part = App.ActiveDocument.Box
FemGui.getActiveAnalysis().Member = FemGui.getActiveAnalysis().Member + [App.ActiveDocument.ActiveObject]
CfdMeshRegion.makeCfdMeshRegion(App.ActiveDocument.Box_CartesianMesh)
#Gui.getDocument("porousZone").getObject("Box").Visibility=False
#Gui.getDocument("porousZone").getObject("Box001").Visibility=True
referenceList = []
part = FreeCAD.ActiveDocument.getObject('Box001')
referenceList.append((part,'Face3'))
part = FreeCAD.ActiveDocument.getObject('Box001')
referenceList.append((part,'Face2'))
part = FreeCAD.ActiveDocument.getObject('Box001')
referenceList.append((part,'Face4'))
part = FreeCAD.ActiveDocument.getObject('Box001')
referenceList.append((part,'Face1'))
part = FreeCAD.ActiveDocument.getObject('Box001')
referenceList.append((part,'Face5'))
part = FreeCAD.ActiveDocument.getObject('Box001')
referenceList.append((part,'Face6'))
FreeCAD.ActiveDocument.MeshRegion.References = referenceList

FreeCAD.ActiveDocument.MeshRegion.RelativeLength = 0.75
FreeCAD.ActiveDocument.MeshRegion.RefinementThickness = '0 mm'
FreeCAD.ActiveDocument.MeshRegion.NumberLayers = 0
FreeCAD.ActiveDocument.MeshRegion.ExpansionRatio = 0.0
FreeCAD.ActiveDocument.MeshRegion.FirstLayerHeight = '0 mm'
FreeCAD.ActiveDocument.MeshRegion.RefinementLevel = 1
FreeCAD.ActiveDocument.MeshRegion.RegionEdgeRefinement = 1
FreeCAD.ActiveDocument.MeshRegion.Baffle = False

FemGui.getActiveAnalysis().Member = FemGui.getActiveAnalysis().Member + [CfdZone.makeCfdPorousZone()]
App.activeDocument().recompute()
p = FreeCAD.ActiveDocument.PorousZone.porousZoneProperties
p['PorousCorrelation'] = 'DarcyForchheimer'
p['D'] = [0.0,0.0,0.0]
p['F'] = [1.0,1.0,1.0]
p['e1'] = [1.0,0.0,0.0]
p['e2'] = [0.0,1.0,0.0]
p['e3'] = [0.0,0.0,1.0]
p['OuterDiameter'] = 0.0
p['TubeAxis'] = [0.0,0.0,1.0]
p['TubeSpacing'] = 0.0
p['SpacingDirection'] = [1.0,0.0,0.0]
p['AspectRatio'] = 1.73
p['VelocityEstimate'] = 0.0
FreeCAD.ActiveDocument.PorousZone.porousZoneProperties = p
FreeCAD.ActiveDocument.PorousZone.partNameList = ['Box001']


FreeCAD.ActiveDocument.Box_CartesianMesh.CharacteristicLengthMax = '50 mm'
FreeCAD.ActiveDocument.Box_CartesianMesh.MeshUtility = 'snappyHexMesh'
FreeCAD.ActiveDocument.Box_CartesianMesh.CellsBetweenLevels = 3
FreeCAD.ActiveDocument.Box_CartesianMesh.EdgeRefinement = 0
FreeCAD.ActiveDocument.Box_CartesianMesh.PointInMesh = {'y': 203.1205, 'x': 258.1111, 'z': 2926.5721}
# Macro End: /home/abogaers/Documents/FreeCADCFDWorkbench/TestCases/macros/porousZone.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
