Gui.activateWorkbench("PartWorkbench")
App.ActiveDocument.addObject("Part::Cylinder","Cylinder")
App.ActiveDocument.ActiveObject.Label = "Cylinder"
App.ActiveDocument.recompute()
App.ActiveDocument.getObject("Cylinder").Height = '100 mm'
App.ActiveDocument.getObject("Cylinder").Placement = App.Placement(App.Vector(100,100,100),App.Rotation(App.Vector(1,0,0),90))
App.ActiveDocument.getObject("Cylinder").Radius = '45 mm'
Gui.activateWorkbench("CfdOFWorkbench")
import FemGui
import CfdZone
FemGui.getActiveAnalysis().addObject(CfdZone.makeCfdPorousZone())
App.activeDocument().recompute()

p = FreeCAD.ActiveDocument.PorousZone.porousZoneProperties
p['PorousCorrelation'] = 'DarcyForchheimer'
p['D'] = [0.0,0.0,0.0]
p['F'] = [100.0,100.0,100.0]
p['e1'] = [1.0,0.0,0.0]
p['e2'] = [0.0,1.0,0.0]
p['e3'] = [0.0,0.0,1.0]
p['OuterDiameter'] = 0.0
p['TubeAxis'] = [0.0,0.0,1.0]
p['TubeSpacing'] = 0.0
p['SpacingDirection'] = [1.0,0.0,0.0]
p['AspectRatio'] = 1.73
p['VelocityEstimate'] = 0.0
FreeCAD.ActiveDocument.PorousZone.porousZoneProperties = p
FreeCAD.ActiveDocument.PorousZone.partNameList = ['Cylinder']
sl = []
sl.append(FreeCAD.ActiveDocument.Cylinder)
FreeCAD.ActiveDocument.PorousZone.shapeList = sl
App.ActiveDocument.recompute()
