import Draft
Gui.activateWorkbench("DraftWorkbench")
pl = App.Placement(App.Vector(250,0,0),App.Rotation(App.Vector(0,1,0),-45))
rec = Draft.makeRectangle(length=87,height=100,placement=pl,face=True,support=None)
Draft.autogroup(rec)

import CfdMeshRegion
CfdMeshRegion.makeCfdMeshRegion(App.ActiveDocument.Fusion_Mesh)
referenceList = []
referenceList.append(('Rectangle','Face1'))
FreeCAD.ActiveDocument.MeshRegion.References = referenceList
FreeCAD.ActiveDocument.MeshRegion.RelativeLength = 0.75
FreeCAD.ActiveDocument.MeshRegion.RefinementThickness = '0 mm'
FreeCAD.ActiveDocument.MeshRegion.NumberLayers = 0
FreeCAD.ActiveDocument.MeshRegion.ExpansionRatio = 0.0
FreeCAD.ActiveDocument.MeshRegion.FirstLayerHeight = '0 mm'
FreeCAD.ActiveDocument.MeshRegion.RefinementLevel = 2
FreeCAD.ActiveDocument.MeshRegion.RegionEdgeRefinement = 1
FreeCAD.ActiveDocument.MeshRegion.Baffle = True
FreeCAD.ActiveDocument.MeshRegion.Internal = False
FreeCAD.ActiveDocument.MeshRegion.InternalRegion = {'BoxLengths': {'y': 0.001, 'x': 0.001, 'z': 0.001}, 'Type': 'Box', 'Center': {'y': 0, 'x': 0.0, 'z': 0}, 'SphereRadius': 0.001}

Gui.activateWorkbench("CfdOFWorkbench")
import CfdFluidBoundary
import FemGui
FemGui.getActiveAnalysis().addObject(CfdFluidBoundary.makeCfdFluidBoundary())
bc = FreeCAD.ActiveDocument.CfdFluidBoundary003.BoundarySettings
bc['BoundaryType'] = 'baffle'
bc['BoundarySubtype'] = 'porousBaffle'
bc['ThermalBoundaryType'] = 'fixedValue'
bc['VelocityIsCartesian'] = True
bc['Ux'] = 0.0
bc['Uy'] = 0.0
bc['Uz'] = 0.0
bc['VelocityMag'] = 0.0
bc['DirectionFace'] = ''
bc['ReverseNormal'] = False
bc['MassFlowRate'] = 0.0
bc['VolFlowRate'] = 0.0
bc['Pressure'] = 0.0
bc['SlipRatio'] = 0.0
bc['Temperature'] = 293.0
bc['HeatFlux'] = 0.0
bc['HeatTransferCoeff'] = 0.0
bc['TurbulenceInletSpecification'] = 'intensityAndLengthScale'
bc['TurbulentKineticEnergy'] = 0.01
bc['SpecificDissipationRate'] = 1.00007366139
bc['TurbulenceIntensity'] = 0.1
bc['TurbulenceLengthScale'] = 0.1
bc['PressureDropCoeff'] = 0.84
bc['ScreenWireDiameter'] = 0.0003
bc['ScreenSpacing'] = 0.0005
bc['PorousBaffleMethod'] = 1
FreeCAD.ActiveDocument.CfdFluidBoundary003.BoundarySettings = bc
FreeCAD.ActiveDocument.CfdFluidBoundary003.Label = 'baffle'
FreeCAD.ActiveDocument.CfdFluidBoundary003.References = []
FreeCAD.ActiveDocument.CfdFluidBoundary003.References.append(('Rectangle', 'Face1'))
FreeCAD.ActiveDocument.recompute()

