Gui.activateWorkbench("CfdOFWorkbench")

import CfdAnalysis
import CfdTools
analysis = CfdAnalysis.makeCfdAnalysis('CfdAnalysis')
CfdTools.setActiveAnalysis(analysis)
import CfdPhysicsSelection
analysis.addObject(CfdPhysicsSelection.makeCfdPhysicsSelection())
import CfdFluidMaterial
analysis.addObject(CfdFluidMaterial.makeCfdFluidMaterial('FluidProperties'))
import CfdInitialiseFlowField
analysis.addObject(CfdInitialiseFlowField.makeCfdInitialFlowField())
import CfdSolverFoam
analysis.addObject(CfdSolverFoam.makeCfdSolverFoam())

import CfdMesh
CfdMesh.makeCfdMesh('Slice_Mesh')
App.ActiveDocument.ActiveObject.Part = App.ActiveDocument.Slice
CfdTools.getActiveAnalysis().addObject(App.ActiveDocument.ActiveObject)

FreeCAD.ActiveDocument.Slice_Mesh.CharacteristicLengthMax = '100 mm'
FreeCAD.ActiveDocument.Slice_Mesh.MeshUtility = 'cfMesh'
FreeCAD.ActiveDocument.Slice_Mesh.ElementDimension = '3D'
FreeCAD.ActiveDocument.Slice_Mesh.CellsBetweenLevels = 3
FreeCAD.ActiveDocument.Slice_Mesh.EdgeRefinement = 1.0
FreeCAD.ActiveDocument.Slice_Mesh.PointInMesh = {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}

import CfdMeshRegion
CfdMeshRegion.makeCfdMeshRegion(App.ActiveDocument.Slice_Mesh)
referenceList = []
referenceList.append(('Shell','Face1'))
referenceList.append(('Shell','Face2'))
referenceList.append(('Shell','Face3'))
referenceList.append(('Shell','Face4'))
referenceList.append(('Shell','Face5'))
referenceList.append(('Shell','Face6'))
referenceList.append(('Shell','Face7'))
referenceList.append(('Shell','Face8'))
referenceList.append(('Shell','Face9'))
referenceList.append(('Shell','Face10'))
referenceList.append(('Shell','Face11'))
referenceList.append(('Shell','Face12'))
referenceList.append(('Shell','Face13'))
referenceList.append(('Shell','Face14'))
referenceList.append(('Shell','Face15'))
referenceList.append(('Shell','Face16'))
referenceList.append(('Shell','Face17'))
referenceList.append(('Shell','Face18'))
referenceList.append(('Shell','Face19'))
referenceList.append(('Shell','Face20'))
referenceList.append(('Shell','Face21'))
referenceList.append(('Shell','Face22'))
referenceList.append(('Shell','Face23'))
referenceList.append(('Shell','Face24'))
referenceList.append(('Shell','Face25'))
referenceList.append(('Shell','Face26'))
referenceList.append(('Shell','Face27'))
referenceList.append(('Shell','Face28'))
referenceList.append(('Shell','Face29'))
referenceList.append(('Shell','Face30'))
referenceList.append(('Shell','Face31'))
referenceList.append(('Shell','Face32'))
referenceList.append(('Shell','Face33'))
referenceList.append(('Shell','Face34'))
referenceList.append(('Shell','Face35'))
referenceList.append(('Shell','Face36'))
referenceList.append(('Shell','Face37'))
referenceList.append(('Shell','Face38'))
referenceList.append(('Shell','Face39'))
referenceList.append(('Shell','Face40'))
referenceList.append(('Shell','Face41'))
referenceList.append(('Shell','Face42'))
referenceList.append(('Shell','Face43'))
referenceList.append(('Shell','Face44'))
referenceList.append(('Shell','Face45'))
referenceList.append(('Shell','Face46'))
referenceList.append(('Shell','Face47'))
referenceList.append(('Shell','Face48'))
referenceList.append(('Shell','Face49'))
referenceList.append(('Shell','Face50'))
referenceList.append(('Shell','Face51'))
referenceList.append(('Shell','Face52'))
referenceList.append(('Shell','Face53'))
referenceList.append(('Shell','Face54'))
referenceList.append(('Shell','Face55'))
referenceList.append(('Shell','Face56'))
referenceList.append(('Shell','Face57'))
referenceList.append(('Shell','Face58'))
referenceList.append(('Shell','Face59'))
referenceList.append(('Shell','Face60'))
referenceList.append(('Shell','Face61'))
referenceList.append(('Shell','Face62'))
referenceList.append(('Shell','Face63'))
referenceList.append(('Shell','Face64'))
referenceList.append(('Shell','Face65'))
referenceList.append(('Shell','Face66'))
referenceList.append(('Shell','Face67'))
referenceList.append(('Shell','Face68'))
referenceList.append(('Shell','Face69'))
referenceList.append(('Shell','Face70'))
referenceList.append(('Shell','Face71'))
referenceList.append(('Shell','Face72'))
referenceList.append(('Shell','Face73'))
referenceList.append(('Shell','Face74'))
referenceList.append(('Shell','Face75'))
referenceList.append(('Shell','Face76'))
referenceList.append(('Shell','Face77'))
referenceList.append(('Shell','Face78'))
referenceList.append(('Shell','Face79'))
referenceList.append(('Shell','Face80'))
referenceList.append(('Shell','Face81'))
referenceList.append(('Shell','Face82'))
referenceList.append(('Shell','Face83'))
referenceList.append(('Shell','Face84'))
referenceList.append(('Shell','Face85'))
referenceList.append(('Shell','Face86'))
referenceList.append(('Shell','Face87'))
referenceList.append(('Shell','Face88'))
referenceList.append(('Shell','Face89'))
referenceList.append(('Shell','Face90'))
referenceList.append(('Shell','Face91'))
referenceList.append(('Shell','Face92'))
referenceList.append(('Shell','Face93'))
referenceList.append(('Shell','Face94'))
referenceList.append(('Shell','Face95'))
referenceList.append(('Shell','Face96'))
referenceList.append(('Shell','Face97'))
referenceList.append(('Shell','Face98'))
referenceList.append(('Shell','Face99'))
referenceList.append(('Shell','Face100'))
referenceList.append(('Shell','Face101'))
referenceList.append(('Shell','Face102'))
referenceList.append(('Shell','Face103'))
referenceList.append(('Shell','Face104'))
referenceList.append(('Shell','Face105'))
referenceList.append(('Shell','Face106'))
referenceList.append(('Shell','Face107'))
referenceList.append(('Shell','Face108'))
referenceList.append(('Shell','Face109'))
referenceList.append(('Shell','Face110'))
referenceList.append(('Shell','Face111'))
referenceList.append(('Shell','Face112'))
referenceList.append(('Shell','Face113'))
referenceList.append(('Shell','Face114'))
referenceList.append(('Shell','Face115'))
referenceList.append(('Shell','Face116'))
referenceList.append(('Shell','Face117'))
referenceList.append(('Shell','Face118'))
referenceList.append(('Shell','Face119'))
referenceList.append(('Shell','Face120'))
referenceList.append(('Shell','Face121'))
referenceList.append(('Shell','Face122'))
referenceList.append(('Shell','Face123'))
referenceList.append(('Shell','Face124'))
referenceList.append(('Shell','Face125'))
referenceList.append(('Shell','Face126'))
referenceList.append(('Shell','Face127'))
referenceList.append(('Shell','Face128'))
referenceList.append(('Shell','Face129'))
referenceList.append(('Shell','Face130'))
referenceList.append(('Shell','Face131'))
referenceList.append(('Shell','Face132'))
referenceList.append(('Shell','Face133'))
referenceList.append(('Shell','Face134'))
FreeCAD.ActiveDocument.MeshRegion.References = referenceList

FreeCAD.ActiveDocument.MeshRegion.RelativeLength = 0.25
FreeCAD.ActiveDocument.MeshRegion.RefinementThickness = '100 mm'
FreeCAD.ActiveDocument.MeshRegion.NumberLayers = 1
FreeCAD.ActiveDocument.MeshRegion.ExpansionRatio = 1.2
FreeCAD.ActiveDocument.MeshRegion.FirstLayerHeight = '0 mm'
FreeCAD.ActiveDocument.MeshRegion.RegionEdgeRefinement = 1.0
FreeCAD.ActiveDocument.MeshRegion.Baffle = False
FreeCAD.ActiveDocument.MeshRegion.Internal = False
FreeCAD.ActiveDocument.MeshRegion.InternalRegion = {'Type': 'Box', 'Center': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'BoxLengths': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'SphereRadius': '0 mm', 'Point1': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'Point2': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'Radius1': '0 mm', 'Radius2': '0 mm'}

Gui.ActiveDocument.getObject("Slice_Mesh").Visibility=False
Gui.ActiveDocument.getObject("Slice").Visibility=True

obj = FreeCAD.ActiveDocument.PhysicsModel
obj.Time = 'Steady'
obj.Flow = 'Incompressible'
obj.Thermal = 'None'
obj.Turbulence = 'RANS'
obj.TurbulenceModel = 'kOmegaSST'
obj.gx = '0 mm/s^2'
obj.gy = '-9810 mm/s^2'
obj.gz = '0 mm/s^2'

FreeCAD.ActiveDocument.FluidProperties.Material = {'Name': 'Air', 'Description': 'Standard air properties at 20 Degrees Celsius and 1 atm', 'Density': '1.20 kg/m^3', 'DynamicViscosity': '1.80e-5 kg/m/s', 'MolarMass': '0.0289643897748887 kg/mol', 'Cp': '1004.703 J/kg/K', 'SutherlandConstant': '1.4579326545176254e-06 kg/m/s/K^0.5', 'SutherlandTemperature': '110.4 K'}

init = FreeCAD.ActiveDocument.InitialiseFields
init.PotentialFoam = True
init.UseInletUPValues = False
init.Ux = '0 mm/s'
init.Uy = '0 mm/s'
init.Uz = '0 mm/s'
init.Pressure = '0 kg/(mm*s^2)'
init.VolumeFractions = {}
init.UseInletTemperatureValues = False
init.Temperature = '293 K'
init.UseInletTurbulenceValues = False
init.omega = '1 rad/s'
init.k = '0.01 m^2/s^2'
init.Inlet = None

import CfdFluidBoundary
CfdTools.getActiveAnalysis().addObject(CfdFluidBoundary.makeCfdFluidBoundary())

bc = FreeCAD.ActiveDocument.CfdFluidBoundary
bc.BoundaryType = 'constraint'
bc.BoundarySubType = 'symmetry'
bc.ThermalBoundaryType = 'fixedValue'
bc.VelocityIsCartesian = True
bc.Ux = '0 mm/s'
bc.Uy = '0 mm/s'
bc.Uz = '0 mm/s'
bc.VelocityMag = '0 mm/s'
bc.DirectionFace = ''
bc.ReverseNormal = False
bc.MassFlowRate = '0 kg/s'
bc.VolFlowRate = '0 mm^3/s'
bc.Pressure = '0 kg/(mm*s^2)'
bc.SlipRatio = '0 '
bc.Temperature = '293 K'
bc.HeatFlux = '0 kg/s^3'
bc.HeatTransferCoeff = '0 kg/(s^3*K)'
bc.TurbulenceInletSpecification = 'intensityAndLengthScale'
bc.TurbulentKineticEnergy = '10000 mm^2/s^2'
bc.SpecificDissipationRate = '57.3 deg/s'
bc.TurbulenceIntensity = '0.1 '
bc.TurbulenceLengthScale = '100 mm'
bc.PorousBaffleMethod = 'porousCoeff'
bc.PressureDropCoeff = '0 '
bc.ScreenWireDiameter = '0.1 mm'
bc.ScreenSpacing = '0 mm'
FreeCAD.ActiveDocument.CfdFluidBoundary.Label = 'constraint'
FreeCAD.ActiveDocument.CfdFluidBoundary.References = []
FreeCAD.ActiveDocument.CfdFluidBoundary.References.append(('Slice', 'Face1'))
FreeCAD.ActiveDocument.recompute()

CfdTools.getActiveAnalysis().addObject(CfdFluidBoundary.makeCfdFluidBoundary())

bc = FreeCAD.ActiveDocument.CfdFluidBoundary001
bc.BoundaryType = 'inlet'
bc.BoundarySubType = 'uniformVelocityInlet'
bc.ThermalBoundaryType = 'fixedValue'
bc.VelocityIsCartesian = True
bc.Ux = '0 mm/s'
bc.Uy = '5000 mm/s'
bc.Uz = '-20000 mm/s'
bc.VelocityMag = '0 mm/s'
bc.DirectionFace = ''
bc.ReverseNormal = True
bc.MassFlowRate = '0 kg/s'
bc.VolFlowRate = '0 mm^3/s'
bc.Pressure = '0 kg/(mm*s^2)'
bc.SlipRatio = '0 '
bc.Temperature = '293 K'
bc.HeatFlux = '0 kg/s^3'
bc.HeatTransferCoeff = '0 kg/(s^3*K)'
bc.TurbulenceInletSpecification = 'intensityAndLengthScale'
bc.TurbulentKineticEnergy = '10000 mm^2/s^2'
bc.SpecificDissipationRate = '57.3 deg/s'
bc.TurbulenceIntensity = '0.1 '
bc.TurbulenceLengthScale = '100 mm'
bc.PorousBaffleMethod = 'porousCoeff'
bc.PressureDropCoeff = '0 '
bc.ScreenWireDiameter = '0.1 mm'
bc.ScreenSpacing = '0 mm'
FreeCAD.ActiveDocument.CfdFluidBoundary001.Label = 'inlet'
FreeCAD.ActiveDocument.CfdFluidBoundary001.References = []
FreeCAD.ActiveDocument.CfdFluidBoundary001.References.append(('Slice', 'Face3'))
FreeCAD.ActiveDocument.CfdFluidBoundary001.References.append(('Slice', 'Face2'))
FreeCAD.ActiveDocument.recompute()


CfdTools.getActiveAnalysis().addObject(CfdFluidBoundary.makeCfdFluidBoundary())

bc = FreeCAD.ActiveDocument.CfdFluidBoundary002
bc.BoundaryType = 'wall'
bc.BoundarySubType = 'slipWall'
bc.ThermalBoundaryType = 'fixedValue'
bc.VelocityIsCartesian = True
bc.Ux = '0 mm/s'
bc.Uy = '0 mm/s'
bc.Uz = '0 mm/s'
bc.VelocityMag = '0 mm/s'
bc.DirectionFace = ''
bc.ReverseNormal = False
bc.MassFlowRate = '0 kg/s'
bc.VolFlowRate = '0 mm^3/s'
bc.Pressure = '0 kg/(mm*s^2)'
bc.SlipRatio = '0 '
bc.Temperature = '293 K'
bc.HeatFlux = '0 kg/s^3'
bc.HeatTransferCoeff = '0 kg/(s^3*K)'
bc.TurbulenceInletSpecification = 'intensityAndLengthScale'
bc.TurbulentKineticEnergy = '10000 mm^2/s^2'
bc.SpecificDissipationRate = '57.3 deg/s'
bc.TurbulenceIntensity = '0.1 '
bc.TurbulenceLengthScale = '100 mm'
bc.PorousBaffleMethod = 'porousCoeff'
bc.PressureDropCoeff = '0 '
bc.ScreenWireDiameter = '0.1 mm'
bc.ScreenSpacing = '0 mm'
FreeCAD.ActiveDocument.CfdFluidBoundary002.Label = 'slip'
FreeCAD.ActiveDocument.CfdFluidBoundary002.References = []
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Slice', 'Face12'))
FreeCAD.ActiveDocument.recompute()

CfdTools.getActiveAnalysis().addObject(CfdFluidBoundary.makeCfdFluidBoundary())

bc = FreeCAD.ActiveDocument.CfdFluidBoundary003
bc.BoundaryType = 'outlet'
bc.BoundarySubType = 'staticPressureOutlet'
bc.ThermalBoundaryType = 'fixedValue'
bc.VelocityIsCartesian = True
bc.Ux = '0 mm/s'
bc.Uy = '0 mm/s'
bc.Uz = '0 mm/s'
bc.VelocityMag = '0 mm/s'
bc.DirectionFace = ''
bc.ReverseNormal = False
bc.MassFlowRate = '0 kg/s'
bc.VolFlowRate = '0 mm^3/s'
bc.Pressure = '0 kg/(mm*s^2)'
bc.SlipRatio = '0 '
bc.Temperature = '293 K'
bc.HeatFlux = '0 kg/s^3'
bc.HeatTransferCoeff = '0 kg/(s^3*K)'
bc.TurbulenceInletSpecification = 'intensityAndLengthScale'
bc.TurbulentKineticEnergy = '10000 mm^2/s^2'
bc.SpecificDissipationRate = '57.3 deg/s'
bc.TurbulenceIntensity = '0.1 '
bc.TurbulenceLengthScale = '100 mm'
bc.PorousBaffleMethod = 'porousCoeff'
bc.PressureDropCoeff = '0 '
bc.ScreenWireDiameter = '0.1 mm'
bc.ScreenSpacing = '0 mm'
FreeCAD.ActiveDocument.CfdFluidBoundary003.Label = 'outlet'
FreeCAD.ActiveDocument.CfdFluidBoundary003.References = []
FreeCAD.ActiveDocument.CfdFluidBoundary003.References.append(('Slice', 'Face4'))
FreeCAD.ActiveDocument.CfdFluidBoundary003.References.append(('Slice', 'Face5'))
FreeCAD.ActiveDocument.recompute()

Gui.ActiveDocument.getObject("Slice").Visibility=True
Gui.ActiveDocument.getObject("Shell").Visibility=False

CfdTools.getActiveAnalysis().addObject(CfdFluidBoundary.makeCfdFluidBoundary())

bc = FreeCAD.ActiveDocument.CfdFluidBoundary004
bc.BoundaryType = 'wall'
bc.BoundarySubType = 'fixedWall'
bc.ThermalBoundaryType = 'fixedValue'
bc.VelocityIsCartesian = True
bc.Ux = '0 mm/s'
bc.Uy = '0 mm/s'
bc.Uz = '0 mm/s'
bc.VelocityMag = '0 mm/s'
bc.DirectionFace = ''
bc.ReverseNormal = False
bc.MassFlowRate = '0 kg/s'
bc.VolFlowRate = '0 mm^3/s'
bc.Pressure = '0 kg/(mm*s^2)'
bc.SlipRatio = '0 '
bc.Temperature = '293 K'
bc.HeatFlux = '0 kg/s^3'
bc.HeatTransferCoeff = '0 kg/(s^3*K)'
bc.TurbulenceInletSpecification = 'intensityAndLengthScale'
bc.TurbulentKineticEnergy = '10000 mm^2/s^2'
bc.SpecificDissipationRate = '57.3 deg/s'
bc.TurbulenceIntensity = '0.1 '
bc.TurbulenceLengthScale = '100 mm'
bc.PorousBaffleMethod = 'porousCoeff'
bc.PressureDropCoeff = '0 '
bc.ScreenWireDiameter = '0.1 mm'
bc.ScreenSpacing = '0 mm'
FreeCAD.ActiveDocument.CfdFluidBoundary004.Label = 'wall'
FreeCAD.ActiveDocument.CfdFluidBoundary004.References = []
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face1'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face2'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face3'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face4'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face5'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face6'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face7'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face8'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face9'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face10'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face11'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face12'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face13'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face14'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face15'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face16'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face17'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face18'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face19'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face20'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face21'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face22'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face23'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face24'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face25'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face26'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face27'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face28'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face29'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face30'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face31'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face32'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face33'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face34'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face35'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face36'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face37'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face38'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face39'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face40'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face41'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face42'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face43'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face44'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face45'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face46'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face47'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face48'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face49'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face50'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face51'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face52'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face53'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face54'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face55'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face56'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face57'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face58'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face59'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face60'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face61'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face62'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face63'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face64'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face65'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face66'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face67'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face68'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face69'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face70'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face71'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face72'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face73'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face74'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face75'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face76'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face77'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face78'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face79'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face80'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face81'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face82'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face83'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face84'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face85'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face86'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face87'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face88'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face89'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face90'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face91'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face92'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face93'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face94'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face95'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face96'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face97'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face98'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face99'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face100'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face101'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face102'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face103'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face104'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face105'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face106'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face107'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face108'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face109'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face110'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face111'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face112'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face113'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face114'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face115'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face116'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face117'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face118'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face119'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face120'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face121'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face122'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face123'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face124'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face125'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face126'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face127'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face128'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face129'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face130'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face131'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face132'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face133'))
FreeCAD.ActiveDocument.CfdFluidBoundary004.References.append(('Shell', 'Face134'))
FreeCAD.ActiveDocument.recompute()

FreeCAD.ActiveDocument.getObject("CfdSolver").Parallel = True
FreeCAD.ActiveDocument.getObject("CfdSolver").ParallelCores = 4
