import CfdMeshRegion
CfdMeshRegion.makeCfdMeshRegion(App.ActiveDocument.Slice_Mesh)
referenceList = []
FreeCAD.ActiveDocument.MeshRegion001.References = referenceList

FreeCAD.ActiveDocument.MeshRegion001.RelativeLength = 0.25
FreeCAD.ActiveDocument.MeshRegion001.RefinementThickness = '0 mm'
FreeCAD.ActiveDocument.MeshRegion001.NumberLayers = 1
FreeCAD.ActiveDocument.MeshRegion001.ExpansionRatio = 1.2
FreeCAD.ActiveDocument.MeshRegion001.FirstLayerHeight = '0 mm'
FreeCAD.ActiveDocument.MeshRegion001.RegionEdgeRefinement = 1.0
FreeCAD.ActiveDocument.MeshRegion001.Baffle = False
FreeCAD.ActiveDocument.MeshRegion001.Internal = True
FreeCAD.ActiveDocument.MeshRegion001.InternalRegion = {'Type': 'Sphere', 'Center': {'x': '0 mm', 'y': '100 mm', 'z': '-350 mm'}, 'BoxLengths': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'SphereRadius': '800 mm', 'Point1': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'Point2': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'Radius1': '0 mm', 'Radius2': '0 mm'}

FreeCAD.ActiveDocument.MeshRegion.RelativeLength = 0.05
FreeCAD.ActiveDocument.MeshRegion.RefinementThickness = '0 mm'
FreeCAD.ActiveDocument.MeshRegion.NumberLayers = 3
FreeCAD.ActiveDocument.MeshRegion.ExpansionRatio = 1.2
FreeCAD.ActiveDocument.MeshRegion.FirstLayerHeight = '0 mm'
FreeCAD.ActiveDocument.MeshRegion.RegionEdgeRefinement = 1
FreeCAD.ActiveDocument.MeshRegion.Baffle = False
FreeCAD.ActiveDocument.MeshRegion.Internal = False
FreeCAD.ActiveDocument.MeshRegion.InternalRegion = {'Type': 'Box', 'Center': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'BoxLengths': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'SphereRadius': '0 mm', 'Point1': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'Point2': {'x': '0 mm', 'y': '0 mm', 'z': '0 mm'}, 'Radius1': '0 mm', 'Radius2': '0 mm'}

CfdMeshRegion.makeCfdMeshRegion(App.ActiveDocument.Slice_Mesh)
referenceList = []
referenceList.append(('Slice','Face55'))
referenceList.append(('Slice','Face14'))
referenceList.append(('Slice','Face6'))
referenceList.append(('Slice','Face7'))
FreeCAD.ActiveDocument.MeshRegion002.References = referenceList

FreeCAD.ActiveDocument.MeshRegion002.RelativeLength = 0.02
FreeCAD.ActiveDocument.MeshRegion002.RefinementThickness = '1 mm'
FreeCAD.ActiveDocument.MeshRegion002.NumberLayers = 1
FreeCAD.ActiveDocument.MeshRegion002.ExpansionRatio = 1.2
FreeCAD.ActiveDocument.MeshRegion002.FirstLayerHeight = '0 mm'
FreeCAD.ActiveDocument.MeshRegion002.RegionEdgeRefinement = 1.0
FreeCAD.ActiveDocument.MeshRegion002.Baffle = False
FreeCAD.ActiveDocument.MeshRegion002.Internal = False
FreeCAD.ActiveDocument.MeshRegion002.InternalRegion = {'Type': 'Box', 'Center': {'x': '0 m', 'y': '0 m', 'z': '0 m'}, 'BoxLengths': {'x': '1e-3 m', 'y': '1e-3 m', 'z': '1e-3 m'}, 'SphereRadius': '1e-3 m', 'Point1': {'x': '0 m', 'y': '0 m', 'z': '0 m'}, 'Point2': {'x': '0 m', 'y': '0 m', 'z': '0 m'}, 'Radius1': '1e-3 m', 'Radius2': '1e-3 m'}
