# -*- coding: utf-8 -*-

# Macro Begin: tubeBundle

import FreeCAD
import _CommandCfdAnalysis
import FemGui
import CfdAnalysis
import CfdPhysicsSelection
import CfdFluidMaterial
import CfdInitialiseFlowField
import CfdSolverFoam
import _CommandCfdMeshCartFromShape
import CfdMeshCart
import _CommandCfdMeshRegion
import CfdMeshRegion
import _CommandCfdFluidBoundary
import CfdFluidBoundary

#Gui.activateWorkbench("CfdFoamWorkbench")
analysis = CfdAnalysis.makeCfdAnalysis('CfdAnalysis')
FemGui.setActiveAnalysis(analysis)
analysis.addObject(CfdPhysicsSelection.makeCfdPhysicsSelection())
analysis.addObject(CfdFluidMaterial.makeCfdFluidMaterial('FluidProperties'))
analysis.addObject(CfdInitialiseFlowField.makeCfdInitialFlowField())
analysis.addObject(CfdSolverFoam.makeCfdSolverFoam())

phys = FreeCAD.ActiveDocument.PhysicsModel.PhysicsModel
phys['Time'] = 'Steady'
phys['Flow'] = 'Incompressible'
phys['Turbulence'] = 'RANS'
phys['TurbulenceModel'] = 'kOmegaSST'
phys['Thermal'] = None
FreeCAD.ActiveDocument.PhysicsModel.PhysicsModel = phys

mat = FreeCAD.ActiveDocument.FluidProperties.Material
mat['Density'] = '1.2 kg/m^3'
mat['DynamicViscosity'] = '1.8e-05 kg/m/s'
FreeCAD.ActiveDocument.FluidProperties.Material = mat

# Values are converted to SI units and stored (eg. m/s)
init = FreeCAD.ActiveDocument.InitialiseFields.InitialVariables
init['PotentialFoam'] = True
init['Ux'] = 0.0
init['Uy'] = 0.0
init['Uz'] = 0.0
init['Pressure'] = 0.0
init['UseInletTurbulenceValues'] = 2
init['omega'] = 1.0
init['k'] = 0.01
FreeCAD.ActiveDocument.InitialiseFields.InitialVariables = init

FreeCAD.ActiveDocument.getObject("OpenFOAM").Parallel = True
FreeCAD.ActiveDocument.getObject("OpenFOAM").ParallelCores = 4
FreeCAD.ActiveDocument.getObject("OpenFOAM").WriteInterval = 50.00000
FreeCAD.ActiveDocument.getObject("OpenFOAM").EndTime = 500.00000

CfdMeshCart.makeCfdMeshCart('Cut_CartesianMesh')
App.ActiveDocument.ActiveObject.Part = App.ActiveDocument.Cut
FemGui.getActiveAnalysis().addObject(App.ActiveDocument.ActiveObject)
FreeCAD.ActiveDocument.Cut_CartesianMesh.CharacteristicLengthMax = '10 mm'
FreeCAD.ActiveDocument.Cut_CartesianMesh.MeshUtility = 'cfMesh'

CfdMeshRegion.makeCfdMeshRegion(App.ActiveDocument.Cut_CartesianMesh)
FreeCAD.ActiveDocument.MeshRegion.RelativeLength = 0.5
FreeCAD.ActiveDocument.MeshRegion.RefinementThickness = '5 mm'
FreeCAD.ActiveDocument.MeshRegion.NumberLayers = 16
FreeCAD.ActiveDocument.MeshRegion.ExpansionRatio = 1.2
FreeCAD.ActiveDocument.MeshRegion.FirstLayerHeight = '0 mm'
referenceList = []
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face7'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face9'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face11'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face13'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face15'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face6'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face25'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face23'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face21'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face19'))
FreeCAD.ActiveDocument.MeshRegion.References = referenceList

CfdMeshRegion.makeCfdMeshRegion(App.ActiveDocument.Cut_CartesianMesh)
FreeCAD.ActiveDocument.MeshRegion001.RelativeLength = 0.75
FreeCAD.ActiveDocument.MeshRegion001.RefinementThickness = '30 mm'
FreeCAD.ActiveDocument.MeshRegion001.NumberLayers = 0
FreeCAD.ActiveDocument.MeshRegion001.ExpansionRatio = 0.0
FreeCAD.ActiveDocument.MeshRegion001.FirstLayerHeight = '0 mm'
referenceList = []
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face6'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face25'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face23'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face21'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face19'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face7'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face9'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face11'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face13'))
part = FreeCAD.ActiveDocument.getObject('Cut')
referenceList.append((part,'Face15'))
FreeCAD.ActiveDocument.MeshRegion001.References = referenceList

FreeCAD.ActiveDocument.recompute()

FemGui.getActiveAnalysis().addObject(CfdFluidBoundary.makeCfdFluidBoundary())
# Values are converted to SI units and stored (eg. m/s)
bc = FreeCAD.ActiveDocument.CfdFluidBoundary.BoundarySettings
bc['BoundaryType'] = 'inlet'
bc['BoundarySubtype'] = 'uniformVelocity'
bc['ThermalBoundaryType'] = 'fixedValue'
bc['VelocityIsCartesian'] = True
bc['Ux'] = 1.0
bc['Uy'] = 0.0
bc['Uz'] = 0.0
bc['VelocityMag'] = 0.0
bc['DirectionFace'] = ''
bc['ReverseNormal'] = False
bc['MassFlowRate'] = 0.0
bc['VolFlowRate'] = 0.0
bc['Pressure'] = 0.0
bc['SlipRatio'] = 0.0
bc['TurbulenceInletSpecification'] = 'intensityAndLengthScale'
bc['TurbulentKineticEnergy'] = 0.01
bc['SpecificDissipationRate'] = 1.0
bc['TurbulenceIntensity'] = 0.05
bc['TurbulenceLengthScale'] = 0.002
bc['PressureDropCoeff'] = 0.0
bc['ScreenWireDiameter'] = 0.0
bc['ScreenSpacing'] = 0.0
bc['PorousBaffleMethod'] = 0
FreeCAD.ActiveDocument.CfdFluidBoundary.BoundarySettings = bc
FreeCAD.ActiveDocument.CfdFluidBoundary.Label = 'inlet'
FreeCAD.ActiveDocument.CfdFluidBoundary.References.append(('Cut', 'Face1'))

FreeCAD.ActiveDocument.recompute()

FemGui.getActiveAnalysis().addObject(CfdFluidBoundary.makeCfdFluidBoundary())
# Values are converted to SI units and stored (eg. m/s)
bc = FreeCAD.ActiveDocument.CfdFluidBoundary001.BoundarySettings
bc['BoundaryType'] = 'outlet'
bc['BoundarySubtype'] = 'staticPressure'
bc['ThermalBoundaryType'] = 'fixedValue'
bc['VelocityIsCartesian'] = True
bc['Ux'] = 0.0
bc['Uy'] = 0.0
bc['Uz'] = 0.0
bc['VelocityMag'] = 0.0
bc['DirectionFace'] = 'Cut:Face17'
bc['ReverseNormal'] = False
bc['MassFlowRate'] = 0.0
bc['VolFlowRate'] = 0.0
bc['Pressure'] = 0.0
bc['SlipRatio'] = 0.0
bc['TurbulenceInletSpecification'] = 'intensityAndLengthScale'
bc['TurbulentKineticEnergy'] = 0.01
bc['SpecificDissipationRate'] = 1.0
bc['TurbulenceIntensity'] = 0.1
bc['TurbulenceLengthScale'] = 0.1
bc['PressureDropCoeff'] = 0.0
bc['ScreenWireDiameter'] = 0.0
bc['ScreenSpacing'] = 0.0
bc['PorousBaffleMethod'] = 0
FreeCAD.ActiveDocument.CfdFluidBoundary001.BoundarySettings = bc
FreeCAD.ActiveDocument.CfdFluidBoundary001.Label = 'outlet'
FreeCAD.ActiveDocument.CfdFluidBoundary001.References.append(('Cut', 'Face17'))

FreeCAD.ActiveDocument.recompute()

FemGui.getActiveAnalysis().addObject(CfdFluidBoundary.makeCfdFluidBoundary())
# Values are converted to SI units and stored (eg. m/s)
bc = FreeCAD.ActiveDocument.CfdFluidBoundary002.BoundarySettings
bc['BoundaryType'] = 'wall'
bc['BoundarySubtype'] = 'fixed'
bc['ThermalBoundaryType'] = 'fixedValue'
bc['VelocityIsCartesian'] = True
bc['Ux'] = 0.0
bc['Uy'] = 0.0
bc['Uz'] = 0.0
bc['VelocityMag'] = 0.0
bc['DirectionFace'] = ''
bc['ReverseNormal'] = False
bc['MassFlowRate'] = 0.0
bc['VolFlowRate'] = 0.0
bc['Pressure'] = 0.0
bc['SlipRatio'] = 0.0
bc['TurbulenceInletSpecification'] = 'intensityAndLengthScale'
bc['TurbulentKineticEnergy'] = 0.01
bc['SpecificDissipationRate'] = 1.0
bc['TurbulenceIntensity'] = 0.1
bc['TurbulenceLengthScale'] = 0.1
bc['PressureDropCoeff'] = 0.0
bc['ScreenWireDiameter'] = 0.0
bc['ScreenSpacing'] = 0.0
bc['PorousBaffleMethod'] = 0
FreeCAD.ActiveDocument.CfdFluidBoundary002.BoundarySettings = bc
FreeCAD.ActiveDocument.CfdFluidBoundary002.Label = 'wall'
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face7'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face9'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face11'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face13'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face15'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face21'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face19'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face23'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face25'))
FreeCAD.ActiveDocument.CfdFluidBoundary002.References.append(('Cut', 'Face6'))

FreeCAD.ActiveDocument.recompute()

# Macro End: tubeBundle
